### PR TITLE
Fixes bug with inview event

### LINKED ISSUE #35: Inview is removed on inview when it should be removed on completion
This currently stops plugins from plugging into the inview and _isVisible attribute

### PR DESCRIPTION
**Pull request by darylhedley**
fixes #35

### CODE REVIEW

**Comment by brian-learningpool** [comment]
+1

**Comment by oliverfoster** [comment]
This is a memory leak. The on("inview") event is not released unless the component is completed.

Should be using the:

```
events: { "inview .component-widget": "inview" }
```

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
